spring:
  # 应用信息
  application:
    name: boot-fast-web
  # master数据源配置项
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://101.132.106.79:3306/test_01?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
  # redis
  redis:
    database: 0
    host: 101.132.106.79
    port: 6666
    # Redis服务器连接密码（默认为空）
    password: ai18358572500ai
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 200
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: -1
        # 连接池中的最大空闲连接
        max-idle: 10
        # 连接池中的最小空闲连接
        min-idle: 0

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: priv.eric.server.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# api接口安全相关参数
api:
  token:
    jwt-secret: kLHisBAx50Lw60SPtAZhHBEmm8aZHZkZpGdXUzwEyr3PVef6
    header: accessToken
    expiration: 7200000
    sign: ERIC2021NJ
  timeout: 60

# 项目功能的开关项
fast-web:
  enabled:
    # xss攻击过滤,不写默认为true
    xss-filter: true
    # 接口安全 防止参数篡改/重放攻击
    api-sec: true
    # hibernate validator参数校验
    hibernate-validator: true






















# 应用服务 WEB 访问端口
server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}





